name: Multi-step Workflow with Matrix

on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: 'Specify the runner to use'
        required: true
        type: string
      sleep_time:
        description: 'Specify sleep time in seconds'
        required: true
        type: number

jobs:
  parallel_jobs:
    runs-on: ${{ github.event.inputs.runs_on }}
    strategy:
      matrix:
        task: [1, 2, 3]
    steps:
      - name: Run Parallel Task ${{ matrix.task }}
        run: |
          echo "Running Parallel Task ${{ matrix.task }}"
          sleep ${{ github.event.inputs.sleep_time }}

  sequential_job_1:
    needs: parallel_jobs
    runs-on: ${{ github.event.inputs.runs_on }}
    steps:
      - name: Run Sequential Task 1
        run: |
          echo "Running Sequential Task 1"
          sleep ${{ github.event.inputs.sleep_time }}

  sequential_job_2:
    needs: sequential_job_1
    runs-on: ${{ github.event.inputs.runs_on }}
    steps:
      - name: Run Sequential Task 2
        run: |
          echo "Running Sequential Task 2"
          sleep ${{ github.event.inputs.sleep_time }}
